//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjOnlineShoppingAPI.Models
{
    using System;
    using System.Collections.Generic;
    //for Serialization
    using System.Runtime.Serialization;
    [DataContract]
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    [DataMember]
        public int orderid { get; set; }
        [DataMember]
        public Nullable<System.DateTime> orderdate { get; set; }
        [DataMember]
        public Nullable<double> billamount { get; set; }
        [DataMember]
        public string customerid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual tblcustomer tblcustomer { get; set; }
    }
}
