//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjOnlineShoppingAPI.Models
{
    using System;
    using System.Collections.Generic;
    //for Serialization
    using System.Runtime.Serialization;
      [DataContract]
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [DataMember]
        public int productid { get; set; }
       [DataMember]
        public string productname { get; set; }
       [DataMember]
        public Nullable<float> unitprice { get; set; }
       [DataMember]
        public Nullable<int> quantity { get; set; }
       [DataMember]
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
